function field(label, id, type = "text", value = "", options) {
  return `<label class="field"><span>${label}</span>${options ? `<select id="${id}">${options.map((x) => `<option ${x === value ? "selected" : ""}>${x}</option>`).join("")}</select>` : `<input id="${id}" type="${type}" value="${value}" placeholder="${label}">`}</label>`;
}
function auth(mode) {
  let login = mode === "login";
  return `<main class="auth"><section class="auth-art"><a class="brand">THERMA<span>TWIN</span></a><div><span class="eyebrow">BATTERY INTELLIGENCE PLATFORM</span><h1>Battery Intelligence.<br><em>Reimagined.</em></h1><p>Configure. Monitor. Understand. Predict.</p></div><div class="orbital"><div class="battery-svg"><i></i><i></i><i></i><i></i><b></b></div><span class="data a">34.8°C</span><span class="data b">421.6V</span></div><small>THERMAL DIGITAL TWIN / v0.3</small></section><section class="auth-form"><div class="auth-box"><a class="brand mobile-brand">THERMA<span>TWIN</span></a><span class="eyebrow">${login ? "WORKSPACE ACCESS" : "CREATE WORKSPACE"}</span><h2>${login ? "Welcome back" : "Create your account"}</h2><p>${login ? "Sign in to your workspace" : "Start configuring your battery intelligence platform."}</p><form id="authForm">${!login ? field("Full Name", "fullName") : ""}${field("Work Email", "email", "email")}${field("Password", "password", "password")}${!login ? field("Confirm Password", "confirm", "password") : ""}${login ? '<div class="form-row"><label class="check"><input type="checkbox"> Remember me</label><a>Forgot password?</a></div>' : ""}<button class="button primary wide">${login ? "Sign In" : "Create Account"}</button>${login ? '<button class="button google wide">G&nbsp;&nbsp; Continue with Google</button>' : ""}</form><p class="switch">${login ? 'New to ThermaTwin? <a data-route="register">Create account</a>' : 'Already have an account? <a data-route="login">Back to Sign In</a>'}</p></div></section></main>`;
}
function wizard(step = 1) {
  let c = TT.config,
    content = [
      `<div class="form-grid">${field("System Name", "sysName", "text", c.name)}${field("Application", "application", "text", c.application, ["Electric Vehicle", "Energy Storage", "Industrial", "Research", "Other"])}${field("Battery Chemistry", "chemistry", "text", c.chemistry, ["Lithium-ion", "LFP", "NMC", "Other"])}</div>`,
      `<div class="form-grid">${field("Number of Modules", "modules", "number", c.modules)}${field("Cells per Module", "cells", "number", c.cellsPerModule)}${field("Electrical Configuration", "electrical", "text", c.electrical)}${field("Nominal Voltage", "voltage", "number", c.nominalVoltage)}</div><div class="calc"><span>TOTAL CELLS</span><strong id="totalCells">${c.modules * c.cellsPerModule}</strong><p><b id="multiply">${c.modules} × ${c.cellsPerModule}</b> cells across configured architecture</p></div><div class="architecture-preview">${moduleGrid({ modules: c.modules, cellsPerModule: c.cellsPerModule }, 1, true)}</div>`,
      `<div class="form-grid">${field("Temperature Warning Limit", "warning", "number", c.warning)}${field("Temperature Critical Limit", "critical", "number", c.critical)}${field("Target ΔT", "target", "number", c.targetDelta)}${field("Cooling Method", "cooling", "text", c.cooling, ["Liquid Cooling", "Air Cooling", "Other"])}${field("Coolant Flow Rate", "flow", "number", c.flow)}</div>`,
      `<div class="review">${Object.entries(c)
        .map(([k, v]) => `<div><span>${k.replace(/([A-Z])/g, " $1")}</span><b>${v}</b></div>`)
        .join("")}<div><span>Total Cells</span><b>${c.modules * c.cellsPerModule}</b></div></div>`,
    ][step - 1];
  return `<div class="page-head"><div><span class="eyebrow">NEW SYSTEM</span><h1>Create Battery System</h1><p>Configure a system-specific digital twin.</p></div></div><div class="wizard-steps">${["Define", "Architecture", "Thermal", "Review"].map((x, i) => `<span class="${i + 1 === step ? "active" : i + 1 < step ? "done" : ""}"><b>${i + 1}</b>${x}</span>`).join("")}</div><section class="panel wizard"><div class="panel-head"><div><span class="eyebrow">STEP ${step} OF 4</span><h2>${["Define your system", "Specify architecture", "Set thermal boundaries", "Review configuration"][step - 1]}</h2></div></div>${content}<div class="wizard-actions">${step > 1 ? '<button class="button ghost" data-wizard="prev">Back</button>' : "<span></span>"}<button class="button primary" data-wizard="next">${step === 4 ? "Create Digital Twin" : "Continue"}</button></div></section>`;
}
